replicaCount: 1

image:
  repository: sandixst/app1:latest
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: 
      paths:
        - path: /
          pathType: Prefix
  tls: []

