   # app1/k8s/deployment.yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: app1
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: app1
     template:
       metadata:
         labels:
           app: app1
       spec:
         containers:
         - name: app1
           image: sandixst/app1:latest
           ports:
           - containerPort: 80